# duplicated
root: /eccube2/html/ # root_urlpath
admin_dir: admin1/ # admin_route
tpl: /eccube2/html/user_data/packages/default/ # front_urlpath
admin_tpl: /eccube2/html/user_data/packages/admin/ # admin_urlpath
image_path: /eccube2/html/upload/save_image/ # image_save_urlpath

# base valiables
root_dir: C:\xampp\htdocs\eccube2
root_urlpath: /eccube2/html
template_code: default

# routing
admin_route: admin1
user_data_route: user_data

# public directory
public_path: /html
public_path_realdir: C:\xampp\htdocs\eccube2/html

# realdir::image
image_save_realdir: C:\xampp\htdocs\eccube2/html/upload/save_image
image_temp_realdir: C:\xampp\htdocs\eccube2/html/upload/temp_image

# realdir::user_data
user_data_realdir: C:\xampp\htdocs\eccube2/html/user_data

# realdir::block
block_default_realdir: C:\xampp\htdocs\eccube2/src/Eccube/Resource/template/default/Block
block_realdir: C:\xampp\htdocs\eccube2/app/template/default/Block

# realdir::template
template_default_realdir: C:\xampp\htdocs\eccube2/src/Eccube/Resource/template/default
template_default_html_realdir: C:\xampp\htdocs\eccube2/html/template/default
template_admin_realdir: C:\xampp\htdocs\eccube2/src/Eccube/Resource/template/admin
template_admin_html_realdir: C:\xampp\htdocs\eccube2/html/template/admin
template_realdir: C:\xampp\htdocs\eccube2/app/template/default
template_html_realdir: C:\xampp\htdocs\eccube2/html/template/default
template_temp_realdir: C:\xampp\htdocs\eccube2/app/cache/eccube/template

# realdir::csv
csv_temp_realdir: C:\xampp\htdocs\eccube2/app/cache/eccube/csv

# realdir:plugin
plugin_realdir: C:\xampp\htdocs\eccube2/app/Plugin
plugin_temp_realdir: C:\xampp\htdocs\eccube2/app/cache/plugin
plugin_html_realdir: C:\xampp\htdocs\eccube2/html/plugin

# urlpath
admin_urlpath: /eccube2/html/template/admin
front_urlpath: /eccube2/html/template/default
image_save_urlpath: /eccube2/html/upload/save_image
image_temp_urlpath: /eccube2/html/upload/temp_image
user_data_urlpath: /eccube2/html/user_data
plugin_urlpath: /eccube2/html/plugin
