<?php

namespace Plugin\AffiliatesPoint\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointRateRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointRateRepository extends EntityRepository
{
/*
    var_dump('Repository Before');
    $app['affiliates_point.repository.point_rate'] = $app->share(function () use ($app) {
            return $app['orm.em']->getRepository('Plugin\AffiliatesPoint\Entity\PointRate');
    });
   var_dump('Repository After');
*/
}
