<?php

namespace Plugin\AffiliatesPoint\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * PointHistoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PointHistoryRepository extends EntityRepository
{
}
